package source

import (
	"context"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"net/netip"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"golang.org/x/net/dns/dnsmessage"
)

func TestParseResolvConf_Standard(t *testing.T) {
	input := `
# Generated by Termux resolv-conf
nameserver 10.0.0.1
nameserver 10.0.0.2
search example.com
`
	servers := parseResolvConf(strings.NewReader(input))
	expected := []string{"10.0.0.1:53", "10.0.0.2:53"}

	if len(servers) != len(expected) {
		t.Fatalf("expected %d servers, got %d: %v", len(expected), len(servers), servers)
	}
	for i, exp := range expected {
		if servers[i] != exp {
			t.Errorf("server[%d]: expected %q, got %q", i, exp, servers[i])
		}
	}
}

func TestParseResolvConf_IPv6(t *testing.T) {
	input := `
nameserver 2606:4700:4700::1111
nameserver [2001:4860:4860::8888]:5353
`
	servers := parseResolvConf(strings.NewReader(input))
	expected := []string{
		"[2606:4700:4700::1111]:53",
		"[2001:4860:4860::8888]:5353",
	}

	if len(servers) != len(expected) {
		t.Fatalf("expected %d servers, got %d: %v", len(expected), len(servers), servers)
	}
	for i, exp := range expected {
		if servers[i] != exp {
			t.Errorf("server[%d]: expected %q, got %q", i, exp, servers[i])
		}
	}
}

func TestParseResolvConf_CommentsAndWhitespace(t *testing.T) {
	input := `
   # Leading spaces comment
; Semicolon comment
nameserver 192.168.1.1 # inline comment
nameserver   192.168.1.2:5353   ; another inline comment
   
`
	servers := parseResolvConf(strings.NewReader(input))
	expected := []string{"192.168.1.1:53", "192.168.1.2:5353"}

	if len(servers) != len(expected) {
		t.Fatalf("expected %d servers, got %d: %v", len(expected), len(servers), servers)
	}
	for i, exp := range expected {
		if servers[i] != exp {
			t.Errorf("server[%d]: expected %q, got %q", i, exp, servers[i])
		}
	}
}

func TestParseResolvConf_InvalidLines(t *testing.T) {
	input := `
nameserver not-an-ip
nameserver
domain local
search test.local
nameserver 127.0.0.53
`
	servers := parseResolvConf(strings.NewReader(input))
	expected := []string{"127.0.0.53:53"}

	if len(servers) != len(expected) {
		t.Fatalf("expected %d servers, got %d: %v", len(expected), len(servers), servers)
	}
	if servers[0] != expected[0] {
		t.Errorf("expected %q, got %q", expected[0], servers[0])
	}
}

func TestParseResolvConf_MaxServers(t *testing.T) {
	input := `
nameserver 10.0.0.1
nameserver 10.0.0.2
nameserver 10.0.0.3
nameserver 10.0.0.4
nameserver 10.0.0.5
`
	servers := parseResolvConf(strings.NewReader(input))
	if len(servers) != maxNameservers {
		t.Fatalf("expected exactly %d servers capped, got %d", maxNameservers, len(servers))
	}
}

func TestLoadResolvConf(t *testing.T) {
	tmpDir := t.TempDir()
	confFile := filepath.Join(tmpDir, "resolv.conf")
	content := "nameserver 1.2.3.4\nnameserver 5.6.7.8\n"
	if err := os.WriteFile(confFile, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write test file: %v", err)
	}

	servers, err := loadResolvConf(confFile)
	if err != nil {
		t.Fatalf("loadResolvConf failed: %v", err)
	}
	if len(servers) != 2 || servers[0] != "1.2.3.4:53" || servers[1] != "5.6.7.8:53" {
		t.Fatalf("unexpected servers: %v", servers)
	}

	// Non-existent path returns error
	_, err = loadResolvConf(filepath.Join(tmpDir, "does-not-exist.conf"))
	if err == nil {
		t.Error("expected error for non-existent file, got nil")
	}
}

func TestTermuxResolvPath_EnvPrefix(t *testing.T) {
	tmpDir := t.TempDir()
	etcDir := filepath.Join(tmpDir, "etc")
	if err := os.MkdirAll(etcDir, 0o755); err != nil {
		t.Fatalf("mkdir failed: %v", err)
	}
	confFile := filepath.Join(etcDir, "resolv.conf")
	if err := os.WriteFile(confFile, []byte("nameserver 1.1.1.1\n"), 0o644); err != nil {
		t.Fatalf("write failed: %v", err)
	}

	origPrefix := os.Getenv("PREFIX")
	defer func() {
		if origPrefix != "" {
			_ = os.Setenv("PREFIX", origPrefix)
		} else {
			_ = os.Unsetenv("PREFIX")
		}
	}()

	_ = os.Setenv("PREFIX", tmpDir)
	foundPath := termuxResolvPath()
	if foundPath != confFile {
		t.Errorf("expected %q, got %q", confFile, foundPath)
	}
}

func TestTermuxResolver_DialsConfiguredServer(t *testing.T) {
	// Start mock UDP listener
	pc, err := net.ListenPacket("udp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("ListenPacket error: %v", err)
	}
	defer pc.Close()

	serverAddr := pc.LocalAddr().String()
	receivedCh := make(chan string, 1)

	go func() {
		buf := make([]byte, 512)
		n, addr, err := pc.ReadFrom(buf)
		if err == nil {
			receivedCh <- fmt.Sprintf("received %d bytes from %v", n, addr)
		}
	}()

	dialer := newResolvDialer([]string{serverAddr})
	if dialer.Resolver == nil {
		t.Fatal("expected non-nil Resolver on dialer")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	// Trigger DNS query; we expect UDP packet to arrive at serverAddr
	_, _ = dialer.Resolver.LookupIPAddr(ctx, "test-lookup.internal")

	select {
	case msg := <-receivedCh:
		t.Logf("verified resolver dialed configured server: %s", msg)
	case <-time.After(1 * time.Second):
		t.Fatal("timeout waiting for DNS query on configured nameserver")
	}
}

func TestTermuxResolver_HermeticDomainResolution(t *testing.T) {
	// 1. Start HTTP test server
	expectedBody := "vless://hermetic-test@127.0.0.1:443#TestNode\n"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(expectedBody))
	}))
	defer srv.Close()

	srvAddrPort, err := netip.ParseAddrPort(srv.Listener.Addr().String())
	if err != nil {
		t.Fatalf("failed to parse server address: %v", err)
	}
	port := srvAddrPort.Port()

	// 2. Start mock DNS responder resolving any A query to 127.0.0.1
	dnsPC, err := net.ListenPacket("udp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to start mock DNS: %v", err)
	}
	defer dnsPC.Close()
	dnsAddr := dnsPC.LocalAddr().String()

	go func() {
		buf := make([]byte, 512)
		for {
			n, clientAddr, err := dnsPC.ReadFrom(buf)
			if err != nil {
				return
			}
			var p dnsmessage.Parser
			header, err := p.Start(buf[:n])
			if err != nil {
				continue
			}
			q, err := p.Question()
			if err != nil {
				continue
			}

			b := dnsmessage.NewBuilder(nil, dnsmessage.Header{
				ID:                 header.ID,
				Response:           true,
				Authoritative:      true,
				RecursionAvailable: true,
			})
			_ = b.StartQuestions()
			_ = b.Question(q)
			_ = b.StartAnswers()
			_ = b.AResource(
				dnsmessage.ResourceHeader{
					Name:  q.Name,
					Type:  dnsmessage.TypeA,
					Class: dnsmessage.ClassINET,
					TTL:   60,
				},
				dnsmessage.AResource{A: [4]byte{127, 0, 0, 1}},
			)
			msg, err := b.Finish()
			if err == nil {
				_, _ = dnsPC.WriteTo(msg, clientAddr)
			}
		}
	}()

	// 3. Build transport configured with the mock nameserver
	tr := newTermuxTransport([]string{dnsAddr})
	if tr == nil {
		t.Fatal("expected non-nil transport")
	}
	if httpTr, ok := tr.(*http.Transport); ok {
		httpTr.Proxy = nil
	}

	client := &http.Client{
		Transport: tr,
		Timeout:   5 * time.Second,
	}

	// 4. Perform HTTP GET using a dummy domain name
	reqURL := "http://hermetic-sub.local:" + strconv.Itoa(int(port)) + "/sub"
	resp, err := client.Get(reqURL)
	if err != nil {
		t.Fatalf("failed to fetch via domain: %v", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	t.Logf("resp.StatusCode=%d resp.Status=%s bodyLen=%d", resp.StatusCode, resp.Status, len(body))
	if err != nil {
		t.Fatalf("failed to read response: %v", err)
	}
	if string(body) != expectedBody {
		t.Errorf("expected body %q, got %q", expectedBody, string(body))
	}
}
